stages:
  - build

build:
  stage: build
  image: maven:3.6.3-jdk-8
  variables:
    MAVEN_OPTS: >-
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
    MAVEN_CLI_OPTS: >-
      --batch-mode
      --errors
      --fail-at-end
      --show-version
      --no-transfer-progress
      -DinstallAtEnd=true
      -DdeployAtEnd=true
  script:
    - SETTINGS_FILE=`find / -name settings.xml`
    - echo $SETTINGS_FILE
    - sed -i "s#</servers>#<server><id>ossrh</id><username>$ossrh_user</username><password>$ossrh_pass</password></server>&#" $SETTINGS_FILE
    - mvn clean package source:jar javadoc:jar deploy -DskipTests=true
  artifacts:
    name: nacos-sentinel
    paths:
      - target/*.jar
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .m2/repository
