server:
  port: ${NACOS_SENTINEL_SERVER_PORT:8080}
---
spring:
  application:
    name: ${NACOS_SENTINEL_SPRING_APPLICATION_NAME:nacos-sentinel}
---
nacos:
  sentinel:
    discovery:
      server-addr: ${NACOS_SENTINEL_DISCOVERY_SERVER_ADDR:127.0.0.1:8848}
      namespace: ${NACOS_SENTINEL_DISCOVERY_NAMESPACE:public}
---
logging:
  level:
    org.springframework.web: debug
    org.apache.coyote.http11: debug
    org.apache.coyote.http2: debug
    cn.com.xuxiaowei.nacos.sentinel: debug
  file:
    name: ${NACOS_SENTINEL_LOGS_FOLDER:/logs}/${spring.application.name}/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: ${NACOS_SENTINEL_LOGS_MAX_FILE_SIZE:20MB}
      max-history: ${NACOS_SENTINEL_LOGS_MAX_HISTORY:365}
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log.gz
