spring:
  application:
    name: nacos-sentinel
---
nacos:
  sentinel:
    discovery:
      server-addr: ${NACOS_SENTINEL_DISCOVERY_SERVER_ADDR:127.0.0.1:8848}
      namespace: ${NACOS_SENTINEL_DISCOVERY_NAMESPACE:public}
